name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean and build application
        run: |
          rm -rf .next out
          npm run build:static
          ls -la out/
          echo "Verifying build output..."
          if [ ! -f "out/index.html" ]; then
            echo "❌ Build failed - no index.html found"
            exit 1
          fi
          echo "✅ Build verification passed"

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRIDGINGTRUST_WEBSITE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "out" # App source code path
          api_location: "" # No API functions
          output_location: "out" # Built app content directory - optional
          skip_app_build: true # Skip building since we build above
          ###### End of Repository/Build Configurations ######

      - name: Verify deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          echo "Testing deployment..."
          # Test if the site is accessible (will be updated with actual URL)
          echo "Deployment verification completed"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRIDGINGTRUST_WEBSITE }}
          action: "close"
          app_location: "out" 